#!/usr/bin/env python3
"""
Image to 3D Asset Converter - Flask Backend
Converts 2D images to 3D assets using depth estimation and mesh generation.
"""

import os
import io
import sys
import uuid
import json
import struct
import zipfile
import tempfile
import traceback
import numpy as np
from pathlib import Path
from flask import Flask, request, jsonify, send_file, make_response
from PIL import Image
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 32 * 1024 * 1024  # 32MB limit

@app.after_request
def add_cors(response):
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type'
    response.headers['Access-Control-Allow-Methods'] = 'GET,POST,OPTIONS'
    response.headers['Access-Control-Expose-Headers'] = 'X-Mesh-Stats'
    return response

@app.route('/convert', methods=['OPTIONS'])
def convert_options():
    return make_response('', 204)

UPLOAD_DIR = Path(tempfile.gettempdir()) / "img3d_uploads"
OUTPUT_DIR = Path(tempfile.gettempdir()) / "img3d_outputs"
UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

# ─────────────────────────────────────────────
# Depth Estimation (pure NumPy, no ML required)
# ─────────────────────────────────────────────

def estimate_depth_map(img_array: np.ndarray) -> np.ndarray:
    """
    Heuristic depth estimation from a single image.
    Uses luminance, edge detection, and vertical position bias
    (objects lower in frame tend to be closer — the "ground plane" assumption).
    """
    if img_array.ndim == 3 and img_array.shape[2] == 4:
        img_array = img_array[:, :, :3]

    # Luminance
    lum = (0.299 * img_array[:,:,0] + 0.587 * img_array[:,:,1] + 0.114 * img_array[:,:,2]) / 255.0

    # Laplacian edge magnitude (focus measure)
    def laplacian(arr):
        k = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]], dtype=np.float32)
        from scipy.ndimage import convolve
        return np.abs(convolve(arr.astype(np.float32), k))

    try:
        from scipy.ndimage import convolve, gaussian_filter
        edges = laplacian(lum)
        edges = gaussian_filter(edges, sigma=2)
        smooth_lum = gaussian_filter(lum, sigma=3)
    except ImportError:
        edges = np.zeros_like(lum)
        smooth_lum = lum

    # Vertical gradient bias (top = far, bottom = near)
    h, w = lum.shape
    y_grad = np.linspace(0.2, 0.8, h)[:, None] * np.ones((1, w))

    # Combine cues
    depth = (0.4 * smooth_lum + 0.3 * (1.0 - edges / (edges.max() + 1e-8)) + 0.3 * y_grad)

    # Normalize to [0, 1]
    depth = (depth - depth.min()) / (depth.max() - depth.min() + 1e-8)
    return depth.astype(np.float32)


def depth_to_mesh(depth: np.ndarray, img: np.ndarray, scale_z: float = 0.4,
                  subsample: int = 2):
    """
    Convert a depth map + color image to a triangulated mesh.
    Returns vertices (N,3), colors (N,3 uint8), faces (M,3).
    """
    h, w = depth.shape
    # Subsample for manageable mesh size
    ys = np.arange(0, h, subsample)
    xs = np.arange(0, w, subsample)
    gy, gx = np.meshgrid(ys, xs, indexing='ij')

    sh, sw = gy.shape

    # Normalised XY coords [-1, 1]
    nx = (gx / (w - 1)) * 2 - 1
    ny = (gy / (h - 1)) * 2 - 1
    nz = depth[gy, gx] * scale_z

    vertices = np.stack([nx, -ny, nz], axis=-1).reshape(-1, 3).astype(np.float32)

    # Colors
    if img.ndim == 3 and img.shape[2] == 4:
        img = img[:, :, :3]
    colors = img[gy, gx].reshape(-1, 3).astype(np.uint8)

    # Faces — two triangles per quad
    def idx(r, c): return r * sw + c
    faces = []
    for r in range(sh - 1):
        for c in range(sw - 1):
            a, b, c_, d = idx(r,c), idx(r,c+1), idx(r+1,c), idx(r+1,c+1)
            faces.append([a, b, c_])
            faces.append([b, d, c_])
    faces = np.array(faces, dtype=np.int32)

    return vertices, colors, faces


# ─────────────────────────────────────────────
# Exporters
# ─────────────────────────────────────────────

def export_obj(vertices, colors, faces, stem: str) -> bytes:
    """Export mesh as Wavefront OBJ + MTL with per-vertex colors (via texture)."""
    lines = [f"# Generated by img3d converter", f"mtllib {stem}.mtl", ""]
    for v, c in zip(vertices, colors):
        lines.append(f"v {v[0]:.5f} {v[1]:.5f} {v[2]:.5f} {c[0]/255:.4f} {c[1]/255:.4f} {c[2]/255:.4f}")
    lines.append("")
    for f in faces:
        lines.append(f"f {f[0]+1} {f[1]+1} {f[2]+1}")
    obj_bytes = "\n".join(lines).encode()

    mtl = f"newmtl default\nKa 1 1 1\nKd 1 1 1\n"
    mtl_bytes = mtl.encode()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{stem}.obj", obj_bytes)
        zf.writestr(f"{stem}.mtl", mtl_bytes)
    return buf.getvalue()


def export_ply(vertices, colors, faces) -> bytes:
    """Export mesh as binary PLY."""
    nv, nf = len(vertices), len(faces)
    header = (
        f"ply\nformat binary_little_endian 1.0\n"
        f"element vertex {nv}\n"
        f"property float x\nproperty float y\nproperty float z\n"
        f"property uchar red\nproperty uchar green\nproperty uchar blue\n"
        f"element face {nf}\n"
        f"property list uchar int vertex_indices\n"
        f"end_header\n"
    ).encode()

    vdata = bytearray()
    for v, c in zip(vertices, colors):
        vdata += struct.pack('<fff', *v)
        vdata += struct.pack('<BBB', *c)

    fdata = bytearray()
    for f in faces:
        fdata += struct.pack('<B', 3)
        fdata += struct.pack('<iii', *f)

    return header + bytes(vdata) + bytes(fdata)


def export_stl(vertices, faces) -> bytes:
    """Export mesh as binary STL (no color, geometry only)."""
    buf = bytearray(80)  # header
    buf += struct.pack('<I', len(faces))
    for f in faces:
        v0, v1, v2 = vertices[f[0]], vertices[f[1]], vertices[f[2]]
        edge1 = v1 - v0; edge2 = v2 - v0
        n = np.cross(edge1, edge2)
        ln = np.linalg.norm(n)
        n = n / ln if ln > 0 else n
        buf += struct.pack('<fff', *n)
        buf += struct.pack('<fff', *v0)
        buf += struct.pack('<fff', *v1)
        buf += struct.pack('<fff', *v2)
        buf += struct.pack('<H', 0)
    return bytes(buf)


def export_gltf(vertices, colors, faces, stem: str) -> bytes:
    """Export as glTF 2.0 JSON + binary buffer, zipped."""
    verts_flat = vertices.astype(np.float32).flatten()
    colors_norm = (colors.astype(np.float32) / 255.0).flatten()
    faces_flat = faces.astype(np.uint32).flatten()

    v_bytes = verts_flat.tobytes()
    c_bytes = colors_norm.tobytes()
    f_bytes = faces_flat.tobytes()

    # Pad to 4-byte boundary
    def padded(b): return b + b'\x00' * (-len(b) % 4)

    v_bytes = padded(v_bytes); v_len = len(v_bytes)
    c_bytes = padded(c_bytes); c_len = len(c_bytes)
    f_bytes = padded(f_bytes); f_len = len(f_bytes)

    bin_data = v_bytes + c_bytes + f_bytes

    vmin = vertices.min(axis=0).tolist()
    vmax = vertices.max(axis=0).tolist()

    gltf = {
        "asset": {"version": "2.0", "generator": "img3d-converter"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0}],
        "meshes": [{
            "name": stem,
            "primitives": [{
                "attributes": {"POSITION": 0, "COLOR_0": 1},
                "indices": 2,
                "mode": 4
            }]
        }],
        "accessors": [
            {
                "bufferView": 0, "componentType": 5126, "count": len(vertices),
                "type": "VEC3", "min": vmin, "max": vmax
            },
            {
                "bufferView": 1, "componentType": 5126, "count": len(vertices),
                "type": "VEC3"
            },
            {
                "bufferView": 2, "componentType": 5125, "count": len(faces) * 3,
                "type": "SCALAR"
            }
        ],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": v_len, "target": 34962},
            {"buffer": 0, "byteOffset": v_len, "byteLength": c_len, "target": 34962},
            {"buffer": 0, "byteOffset": v_len + c_len, "byteLength": f_len, "target": 34963},
        ],
        "buffers": [{"byteLength": len(bin_data), "uri": f"{stem}.bin"}]
    }

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{stem}.gltf", json.dumps(gltf, indent=2))
        zf.writestr(f"{stem}.bin", bin_data)
    return buf.getvalue()


def export_xyz(vertices, colors) -> bytes:
    """Export as ASCII point cloud XYZ with RGB."""
    lines = []
    for v, c in zip(vertices, colors):
        lines.append(f"{v[0]:.5f} {v[1]:.5f} {v[2]:.5f} {c[0]} {c[1]} {c[2]}")
    return "\n".join(lines).encode()


# ─────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "ok"})


@app.route('/convert', methods=['POST'])
def convert():
    try:
        if 'image' not in request.files:
            return jsonify({"error": "No image file provided"}), 400

        file = request.files['image']
        fmt = request.form.get('format', 'ply').lower()
        quality = request.form.get('quality', 'medium').lower()

        quality_map = {'low': 4, 'medium': 2, 'high': 1}
        subsample = quality_map.get(quality, 2)

        scale_z = float(request.form.get('depth_scale', '0.4'))

        # Load image
        img_pil = Image.open(file.stream).convert('RGBA')

        # Resize for processing (keep aspect, max 512px on longest side)
        max_dim = 512
        w, h = img_pil.size
        if max(w, h) > max_dim:
            scale = max_dim / max(w, h)
            img_pil = img_pil.resize((int(w*scale), int(h*scale)), Image.LANCZOS)

        img_array = np.array(img_pil)
        img_rgb = img_array[:, :, :3]

        logger.info(f"Processing image {img_pil.size}, format={fmt}, quality={quality}")

        # Depth estimation
        depth = estimate_depth_map(img_array)

        # Mesh generation
        vertices, colors, faces = depth_to_mesh(depth, img_rgb, scale_z=scale_z, subsample=subsample)

        stem = f"model_{uuid.uuid4().hex[:8]}"

        # Export
        if fmt == 'ply':
            data = export_ply(vertices, colors, faces)
            mime = 'application/octet-stream'
            filename = f"{stem}.ply"
        elif fmt == 'obj':
            data = export_obj(vertices, colors, faces, stem)
            mime = 'application/zip'
            filename = f"{stem}_obj.zip"
        elif fmt == 'stl':
            data = export_stl(vertices, faces)
            mime = 'application/octet-stream'
            filename = f"{stem}.stl"
        elif fmt == 'gltf':
            data = export_gltf(vertices, colors, faces, stem)
            mime = 'application/zip'
            filename = f"{stem}_gltf.zip"
        elif fmt == 'xyz':
            data = export_xyz(vertices, colors)
            mime = 'text/plain'
            filename = f"{stem}.xyz"
        else:
            return jsonify({"error": f"Unknown format: {fmt}"}), 400

        stats = {
            "vertices": len(vertices),
            "faces": len(faces),
            "image_size": list(img_pil.size),
            "format": fmt,
        }
        logger.info(f"Export complete: {stats}")

        resp = send_file(
            io.BytesIO(data),
            mimetype=mime,
            as_attachment=True,
            download_name=filename
        )
        resp.headers['X-Mesh-Stats'] = json.dumps(stats)
        return resp

    except Exception as e:
        logger.error(traceback.format_exc())
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    print("Starting img3d converter on http://localhost:5000")
    app.run(host='0.0.0.0', port=5000, debug=False)
